# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 11:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapitreBible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('titre', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LivreBible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Testament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_na', models.CharField(choices=[('NV', 'Nouveau Testament'), ('AC', 'Ancien Testament')], default='nv', max_length=2)),
                ('titre', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='chapitrebible',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibleEnKabyle.LivreBible'),
        ),
        migrations.AddField(
            model_name='chapitrebible',
            name='testament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibleEnKabyle.Testament'),
        ),
    ]
