# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0002_auto_20161005_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='chapitrebible',
            name='testament',
        ),
        migrations.AddField(
            model_name='chapitrebible',
            name='type_na',
            field=models.CharField(choices=[('NV', 'Nouveau Testament'), ('AC', 'Ancien Testament')], default='nv', max_length=2),
        ),
        migrations.DeleteModel(
            name='Testament',
        ),
    ]
