# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0003_auto_20161005_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrebible',
            name='titre',
            field=models.CharField(blank=True, max_length=250, verbose_name='Titre du livre a ajouter'),
        ),
    ]
