# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 06:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0004_auto_20161005_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('titre', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=250, verbose_name='Titre du livre a ajouter')),
                ('type_na', models.CharField(choices=[('NV', 'Nouveau Testament'), ('AC', 'Ancien Testament')], default='nv', max_length=2)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BibleEnKabyle.LivreBible')),
            ],
        ),
    ]
