# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0005_chapitre_livre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='livre',
        ),
        migrations.AddField(
            model_name='livre',
            name='chapitres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BibleEnKabyle.Chapitre'),
            preserve_default=False,
        ),
    ]
