# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0006_auto_20161007_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitrebible',
            name='type_na',
        ),
        migrations.AddField(
            model_name='livrebible',
            name='type_na',
            field=models.CharField(choices=[('NV', 'Nouveau Testament'), ('AC', 'Ancien Testament')], default='nv', max_length=2),
        ),
    ]
