# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0007_auto_20161007_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='chapitres',
        ),
        migrations.AddField(
            model_name='chapitrebible',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.DeleteModel(
            name='Chapitre',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
