# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 16:45
from __future__ import unicode_literals

import BibleEnKabyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0008_auto_20161010_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitrebible',
            name='audio',
            field=models.FileField(default='', upload_to=BibleEnKabyle.models.audio_upload_files),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livrebible',
            name='slug',
            field=models.SlugField(default='2'),
        ),
        migrations.AlterField(
            model_name='chapitrebible',
            name='slug',
            field=models.SlugField(default='1'),
        ),
    ]
