# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleEnKabyle', '0009_auto_20161013_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitrebible',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='livrebible',
            name='slug',
            field=models.SlugField(),
        ),
    ]
