# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 12:48
from __future__ import unicode_literals

import EnseignementsBibliques.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250)),
                ('prenom', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='EnseignementBiblique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('AD', 'Audio'), ('VI', 'Vid\xe9o')], default='vi', max_length=2)),
                ('content', ckeditor.fields.RichTextField()),
                ('titre', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField()),
                ('media', models.FileField(upload_to=EnseignementsBibliques.models.media_upload_files)),
                ('poster', models.FileField(default='', upload_to=EnseignementsBibliques.models.media_upload_files)),
                ('titre_media', models.CharField(blank=True, max_length=250)),
                ('auteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EnseignementsBibliques.Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='enseignementbiblique',
            name='theme',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EnseignementsBibliques.Theme'),
        ),
                migrations.CreateModel(
            name='EglisePartenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField()),
                ('media', models.FileField(upload_to=EnseignementsBibliques.models.images_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onglet', models.CharField(choices=[('EBTNE', 'Eglise Bethnoe'), ('EGPTR', 'Eglise partenaire'), ('BLKBL', 'Bible en Kabyle'), ('ETDBB', 'Etudes bibliques'), ('ENSBI', 'Enseignements bibliques'), ('LOUAN', 'Louanges'), ('FORUM', 'Forum'), ('LIENS', 'Liens'), ('ACUIL', 'Accueil')], default='EBTNE', max_length=6)),
                ('titre', models.CharField(blank=True, max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('media', models.FileField(upload_to=EnseignementsBibliques.models.fond_upload)),
                ('logo', models.FileField(default='', upload_to=EnseignementsBibliques.models.fond_upload)),
            ],
        ),
    ]
