# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 12:50
from __future__ import unicode_literals

import EnseignementsBibliques.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnseignementsBibliques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignementbiblique',
            name='poster',
        ),
        migrations.AddField(
            model_name='enseignementbiblique',
            name='image',
            field=models.FileField(default='', upload_to=EnseignementsBibliques.models.media_upload_files),
        ),
    ]
