# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnseignementsBibliques', '0002_auto_20161026_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eglisepartenaire',
            options={'managed': False},
        ),
    ]
