# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnseignementsBibliques', '0003_auto_20170826_2126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eglisepartenaire',
            table='EnseignementsBibliques_eglisepartenaire',
        ),
    ]
