# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnseignementsBibliques', '0004_auto_20170826_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignementbiblique',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='enseignementbiblique',
            name='type_media',
            field=models.CharField(choices=[('AD', 'Audio'), ('VI', 'Vid\xe9o'), ('YT', 'YOUTUBE')], default='vi', max_length=2),
        ),
    ]
