# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 12:51
from __future__ import unicode_literals

import EgliseBethnoe.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DirigentEgliseBethnoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('mail', models.EmailField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', EgliseBethnoe.fields.ThumbnailImageField(upload_to='')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('slug', models.SlugField(max_length=64)),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'get_latest_by': 'created_at',
                'permissions': (('view_post', 'Can view post'),),
            },
        ),
        migrations.CreateModel(
            name='FondEcran',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EgliseBethnoe.Image')),
                ('afficher', models.CharField(choices=[('oui', 'Afficher dans la page Home'), ('non', 'Ne pas l afficher dans la page Home')], default='oui', max_length=3)),
                ('caption', models.CharField(blank=True, max_length=250)),
            ],
            bases=('EgliseBethnoe.image',),
        ),
        migrations.CreateModel(
            name='ImageCarrousel',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EgliseBethnoe.Image')),
                ('afficher', models.CharField(choices=[('oui', 'Afficher dans la page Home'), ('non', 'Ne pas l afficher dans la page Home')], default='oui', max_length=3)),
                ('caption', models.CharField(blank=True, max_length=250)),
            ],
            bases=('EgliseBethnoe.image',),
        ),
    ]
