# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 13:21
from __future__ import unicode_literals

import EgliseBethnoe.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAccueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', EgliseBethnoe.fields.ThumbnailImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('afficher', models.CharField(choices=[('oui', 'Afficher dans la page Home'), ('non', 'Ne pas l afficher dans la page Home')], default='oui', max_length=3)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
