# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 11:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEgliseBethnoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=64, verbose_name='titre du bas au milieu')),
                ('content', ckeditor.fields.RichTextField()),
                ('video_url', models.URLField(verbose_name="Url de la video de pr\xe9sentation de l'\xe9glise")),
            ],
        ),
    ]
