# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='afficher',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.CreateModel(
            name='FondEcran',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EgliseBethnoe.Image')),
                ('afficher', models.CharField(choices=[('oui', 'Afficher dans la page Home'), ('non', 'Ne pas l afficher dans la page Home')], default='oui', max_length=3)),
                ('caption', models.CharField(blank=True, max_length=250)),
            ],
            bases=('EgliseBethnoe.image',),
        ),

    ]
