# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirigenteglisebethnoe',
            name='id',
        ),
        migrations.AddField(
            model_name='dirigenteglisebethnoe',
            name='photo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EgliseBethnoe.Image'),
        ),
    ]
