# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0002_indexeglisebethnoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeglisebethnoe',
            name='title2',
            field=models.CharField(default='', max_length=64, verbose_name='titre du bas au milieu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexeglisebethnoe',
            name='title1',
            field=models.CharField(max_length=64, verbose_name='title du haut a gauche'),
        ),
    ]
