# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0002_auto_20161001_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirigenteglisebethnoe',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dirigenteglisebethnoe',
            name='photo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='EgliseBethnoe.Image'),
        ),
    ]
