# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 12:07
from __future__ import unicode_literals

import EgliseBethnoe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0003_auto_20161029_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeglisebethnoe',
            name='logo',
            field=models.FileField(default='', upload_to=EgliseBethnoe.models.audio_upload_files),
            preserve_default=False,
        ),
    ]
