# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 12:46
from __future__ import unicode_literals

import EgliseBethnoe.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0005_auto_20161029_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ImageEvenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=EgliseBethnoe.models.audio_upload_files, verbose_name='Photo ')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EgliseBethnoe.Album')),
                ('image_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EgliseBethnoe.ImageEvenement')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(through='EgliseBethnoe.PhotoDe', to='EgliseBethnoe.ImageEvenement'),
        ),
    ]
