# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0005_auto_20161002_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='num_rue',
            field=models.IntegerField(blank=True),
        ),
    ]
