# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 21:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0007_auto_20161030_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', ckeditor.fields.RichTextField()),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EgliseBethnoe.Album')),
            ],
        ),
    ]
