# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0008_auto_20161003_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fondecran',
            options={'verbose_name': 'Fond d ecran', 'verbose_name_plural': 'Fonds d ecrans'},
        ),
    ]
