# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0008_evenement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='title',
            new_name='titre',
        ),
    ]
