# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0009_auto_20161030_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
