# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0010_evenement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='type_evenments',
            field=models.CharField(choices=[('CF', 'Communication fraternelle'), ('MR', 'Mariages'), ('BE', "B\xe2t\xeame d'eau"), ('GD', 'Gu\xe9risons et d\xe9livrance')], default='CF', max_length=2),
        ),
    ]
