# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 01:48
from __future__ import unicode_literals

import EgliseBethnoe.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0013_auto_20161103_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='audio',
            new_name='audios',
        ),
        migrations.AddField(
            model_name='audioducd',
            name='Contient',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='liste_lecture', to='EgliseBethnoe.Audio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='titre',
            field=models.CharField(blank=True, max_length=250, verbose_name='Titre du CD, Titre du fichier'),
        ),
        migrations.AlterField(
            model_name='cd',
            name='slug',
            field=models.SlugField(verbose_name='Slug (G\xe9n\xe9r\xe9 automatiquement)'),
        ),
        migrations.AlterField(
            model_name='cd',
            name='titre',
            field=models.CharField(blank=True, max_length=250, verbose_name='Titre du louange (nom du CD)'),
        ),
        migrations.AlterField(
            model_name='imageevenement',
            name='image',
            field=models.FileField(upload_to=EgliseBethnoe.models.audio_upload_files, verbose_name='Photo '),
        ),
        migrations.AlterField(
            model_name='indexeglisebethnoe',
            name='fond_ecran',
            field=models.FileField(upload_to=EgliseBethnoe.models.audio_upload_files, verbose_name='Fond d ecran'),
        ),
        migrations.AlterField(
            model_name='indexeglisebethnoe',
            name='logo',
            field=models.FileField(upload_to=EgliseBethnoe.models.audio_upload_files, verbose_name='Logo '),
        ),
    ]
