# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 12:57
from __future__ import unicode_literals

import EgliseBethnoe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0015_auto_20161104_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='1', upload_to=EgliseBethnoe.models.image_post_upload_files, verbose_name="Image de l'nnonce "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageevenement',
            name='image',
            field=models.FileField(upload_to=EgliseBethnoe.models.images_upload_files, verbose_name='Photo '),
        ),
        migrations.AlterField(
            model_name='indexeglisebethnoe',
            name='fond_ecran',
            field=models.FileField(upload_to=EgliseBethnoe.models.logo_upload_files, verbose_name='Fond d ecran'),
        ),
        migrations.AlterField(
            model_name='indexeglisebethnoe',
            name='logo',
            field=models.FileField(upload_to=EgliseBethnoe.models.logo_upload_files, verbose_name='Logo '),
        ),
    ]
