# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 13:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0016_auto_20161104_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rich',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
