# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 14:18
from __future__ import unicode_literals

import EgliseBethnoe.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0017_post_content_rich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('slug', models.SlugField(max_length=64)),
                ('content', models.TextField(verbose_name='content')),
                ('content_rich', ckeditor.fields.RichTextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', models.FileField(upload_to=EgliseBethnoe.models.image_post_upload_files, verbose_name="Image de l'nnonce ")),
            ],
            options={
                'get_latest_by': 'created_at',
                'permissions': (('view_post', 'Can view post'),),
            },
        ),
    ]
