# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 14:21
from __future__ import unicode_literals

import EgliseBethnoe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0018_priere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priere',
            name='content_rich',
        ),
        migrations.AlterField(
            model_name='priere',
            name='image',
            field=models.FileField(upload_to=EgliseBethnoe.models.image_priere_upload_files, verbose_name="Image de l'nnonce "),
        ),
    ]
