# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 14:36
from __future__ import unicode_literals

import EgliseBethnoe.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0019_auto_20161104_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionDeFoie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Titre Culte Hebdomadaire : ')),
                ('content', ckeditor.fields.RichTextField()),
                ('logo', models.FileField(upload_to=EgliseBethnoe.models.logo_upload_files, verbose_name='Logo ')),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
    ]
