# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0020_confessiondefoie'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirigenteglisebethnoe',
            name='lien',
            field=models.URLField(default='r', verbose_name='Url sur laquelle pointe le role'),
            preserve_default=False,
        ),
    ]
