# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 17:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0022_auto_20161107_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre_Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lien_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Texte du bouton')),
                ('slug', models.SlugField(max_length=150)),
                ('url', models.URLField(verbose_name='Url du lien')),
            ],
        ),
        migrations.CreateModel(
            name='LienDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre_lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EgliseBethnoe.Chapitre_Lien')),
                ('lie_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_chapitre', to='EgliseBethnoe.Lien_c')),
                ('url_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EgliseBethnoe.Lien_c')),
            ],
        ),
        migrations.AddField(
            model_name='chapitre_lien',
            name='lien',
            field=models.ManyToManyField(through='EgliseBethnoe.LienDe', to='EgliseBethnoe.Lien_c'),
        ),
    ]
