# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EgliseBethnoe', '0023_auto_20161115_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre_lien',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='Titre'),
            preserve_default=False,
        ),
    ]
